# if true, the demo data will be used for the simulation, use default data: "chattanooga"
# or string of the name of the demo data, we provide a list of demo data ["chattanooga",]
demo_data:

input_dir: datasets/example2
output_dir:  # optional
Network:
    NetworkName: chatt  # the name of the network should not have space between words
    # polygon points for the network in the format of [lon, lat]
    NetworkVertices: [[-85.14977588011192, 35.040346288414916], [-85.15823020212477, 35.04345144844759], [-85.15829457513502, 35.043293338482925], [-85.14986171079225, 35.04018378032611]]
Traffic: GridSmart
Control: Synchro_signal.csv
Calibration:
    # overall configuration for the calibration
    scenario_config:
        sim_start_time: 28800  # 8:00 AM In seconds
        sim_end_time: 32400  # 9:00 AM In seconds
        calibration_target:
            GEH: 5  # https://en.wikipedia.org/wiki/GEH_statistic
            GEHPercent: 0.85  # accepted match
        calibration_time_step: 1
        allow_u_turn: false  # if true, the u-turns are allowed in the simulation

    turn_inflow:
        max_inflow: 200  # max inflow for the turning ratio

    behavior:
        initial_params:
            min_gap: 2.5  # min gap between vehicles in meters [1,3]
            acceleration: 2.6  #  max acceleration in m/s^2 [2.5,3.0]
            deceleration: 4.5  # max deceleration in m/s^2 [4.0,5.3]
            sigma: 0.5  # driver imperfection [0.0,1.0]
            tau: 1.00  # desired headway time in seconds [0.25,1.25]
            emergencyDecel: 9.0  # emergency deceleration in m/s^2 [5.0,9.3]

    ga_config:  # generic algorithm configuration
        model_selection: "BaseGA"  #  BaseGA, EliteSingleGA, EliteMultiGA, MultiGA, SingleGA
        epoch: 10  # number of generations [1, 100000]
        pop_size: 10  # population size [10, 10000]
        pc: 0.75  # crossover probability [0.7, 0.95]
        pm: 0.1  # mutation probability [0.01, 0.2]

    sa_config:  # simulated annealing configuration
        model_selection: "OriginalSA"  # OriginalSA, GaussianSA, SwarmSA
        epoch: 10  # number of generations [1, 10000]
        temp_init: 100  # initial temperature [1, 10000]
        cooling_rate: 0.891  # same as previous [0, 1]
        step_size: 0.1  # step size for the random movement [-100, 100]
        scale: 0.1  # scale for the temperature [0, 1], GaussianSA and SwarmSA Only

    ts_config:  # tabu search configuration
        epoch: 10  # number of generations [1, 10000]
        tabu_size: 10  # maximum size of the tabu list [2, 10000]
        neighbour_size: 10  # size of the neighborhood for generating candidate solutions [2, 10000]
        perturbation_scale: 0.05  # scale of perturbation for the solution [0, 100]
